export const chapters = [
    {
      "name": "Alpha Xi",
      members: [
        { id: 1, name: "Abhinav Bapanapalli", linkedin: "https://www.linkedin.com/in/abhinav-bapanapalli" },
        { id: 2, name: "Agnik Banerjee", linkedin: "https://www.linkedin.com/in/agnikbanerjee/" },
        { id: 3, name: "Alan Deng", linkedin: "https://www.linkedin.com/in/alandeng1/" },
        { id: 4, name: "Amir Edris", linkedin: "https://www.linkedin.com/in/amir-edris-5a7946329/" },
        { id: 5, name: "Ankit Nakhawa", linkedin: "https://www.linkedin.com/in/ankit-nakhawa" },
        { id: 6, name: "Anna Lim", linkedin: "https://www.linkedin.com/in/anna-lim27/" },
        { id: 7, name: "Anya Zhang", linkedin: "https://www.linkedin.com/in/anyazhng/" },
        { id: 8, name: "Aryan Jain", linkedin: "https://www.linkedin.com/in/aryan-jain" },
        { id: 9, name: "Ben Henigan", linkedin: "https://www.linkedin.com/in/benhenigan/" },
        { id: 10, name: "Bryce Powell", linkedin: "https://www.linkedin.com/in/powellbryce/" },
        { id: 11, name: "Cayetana (Cate) Areas Barcenas", linkedin: "https://www.linkedin.com/in/cayetana-areas-0889472a5/" },
        { id: 12, name: "Dennise Lopez Gonzales", linkedin: "https://www.linkedin.com/in/dennise-lopez-gonzales" },
        { id: 13, name: "Edwin Cao", linkedin: "https://www.linkedin.com/in/edwin-cao0/" },
        { id: 14, name: "Emely Martinez", linkedin: "https://www.linkedin.com/in/emely-martinez" },
        { id: 15, name: "Hashem Alomar", linkedin: "https://www.linkedin.com/in/hashem-alomar/" },
        { id: 16, name: "Jack Mason", linkedin: "https://www.linkedin.com/in/jackmason13/" },
        { id: 17, name: "Linh Ngo", linkedin: "https://www.linkedin.com/in/linh-ngo" },
        { id: 18, name: "Nidhin Gangisetty", linkedin: "https://www.linkedin.com/in/nidhin-gangisetty" },
        { id: 19, name: "Noah Combatir", linkedin: "https://www.linkedin.com/in/noah-combatir/" },
        { id: 20, name: "Patrick Zhang", linkedin: "https://www.linkedin.com/in/patrick-zhang" },
        { id: 21, name: "Rishi Chudasama", linkedin: "https://www.linkedin.com/in/rishi-chudasama/" },
        { id: 22, name: "Riyana Patel", linkedin: "https://www.linkedin.com/in/riyana-patel-9488aa326/" },
        { id: 23, name: "Ryan Krucenski", linkedin: "https://www.linkedin.com/in/ryankrucenski/" },
        { id: 24, name: "Shengyu Tan", linkedin: "https://www.linkedin.com/in/shengyutan/" },
        { id: 25, name: "Sriman Sista", linkedin: "https://www.linkedin.com/in/sriman-sista" },
        { id: 26, name: "Vaishnavi Banda", linkedin: "https://www.linkedin.com/in/vaishnavi-banda/" }
      ]
    },
    {
      "name": "Alpha Nu",
      members: [
        { id: 1, name: "Aditya Waikar", linkedin: "https://www.linkedin.com/in/aditya-waikar-998373211/" },
        { id: 2, name: "Alexis Iwuchukwu", linkedin: "https://www.linkedin.com/in/alexisiwuchukwu/" },
        { id: 3, name: "Ashley Woo", linkedin: "https://www.linkedin.com/in/ashley-woo" },
        { id: 4, name: "Ayush Gawane", linkedin: "https://www.linkedin.com/in/ayush-gawane/" },
        { id: 5, name: "Bryan Haddad", linkedin: "https://www.linkedin.com/in/bryanhaddad/" },
        { id: 6, name: "Hasan Ege", linkedin: "https://www.linkedin.com/in/hasan-ege-2aa35921b/" },
        { id: 7, name: "Hamid Shabbir", linkedin: "https://www.linkedin.com/in/hamidshabbir1/" },
        { id: 8, name: "Inaya Siddiqi", linkedin: "https://www.linkedin.com/in/inaya-siddiqi" },
        { id: 9, name: "Jeffery Wei", linkedin: "https://www.linkedin.com/in/jefferywei/" },
        { id: 10, name: "Joao Eduardo Camargo de Miranda", linkedin: "https://www.linkedin.com/in/joao-eduardo-camargo-de-miranda-80b902258/" },
        { id: 11, name: "Julianne Tinana", linkedin: "https://www.linkedin.com/in/julianne-tinana" },
        { id: 12, name: "Megan Walker", linkedin: "https://www.linkedin.com/in/mwalker3155/" },
        { id: 13, name: "Nancy Puthenpurayil", linkedin: "https://www.linkedin.com/in/nancy-puthenpurayil/" },
        { id: 14, name: "Nihar Xavier", linkedin: "https://www.linkedin.com/in/niharxavier/" },
        { id: 15, name: "Nikhita Karthikesan", linkedin: "https://www.linkedin.com/in/nikhita-karthikesan" },
        { id: 16, name: "Odera Okafor", linkedin: "https://www.linkedin.com/in/odera-okafor" },
        { id: 17, name: "Rishika Patibandla", linkedin: "https://www.linkedin.com/in/rishika-patibandla" },
        { id: 18, name: "Ritika Pokharel", linkedin: "https://www.linkedin.com/in/ritika-pokharel133/" },
        { id: 19, name: "Rubani Singh", linkedin: "https://www.linkedin.com/in/rubani-singh" },
        { id: 20, name: "Shravya Kundavaram", linkedin: "https://www.linkedin.com/in/shravya-kundavaram" },
        { id: 21, name: "Sreenidhi Yaratha", linkedin: "https://www.linkedin.com/in/sreenidhi-yaratha-4b0795203/" }
      ]
    },
    {
      "name": "Alpha Mu",
      members: [
        { id: 1, name: "Abhiram Sreeramaneni", linkedin: "https://www.linkedin.com/in/abhiram-sreeramaneni" },
        { id: 2, name: "Arsha Garg", linkedin: "https://www.linkedin.com/in/arsha-garg/" },
        { id: 3, name: "Avni Kaushik", linkedin: "https://www.linkedin.com/in/avni-kaushik" },
        { id: 4, name: "Eileen Zhang", linkedin: "https://www.linkedin.com/in/eileen-zh/" },
        { id: 5, name: "Ethan Grossman", linkedin: "https://www.linkedin.com/in/ethan-grossman" },
        { id: 6, name: "Fynn Anderson", linkedin: "https://www.linkedin.com/in/fynn-anderson-50a78722b/" },
        { id: 7, name: "Gurnoor Gill", linkedin: "https://www.linkedin.com/in/gurnoor-gill" },
        { id: 8, name: "Jake Hofmann", linkedin: "https://www.linkedin.com/in/jakeh04/" },
        { id: 9, name: "Jinan Yousuf", linkedin: "https://www.linkedin.com/in/jinan-yousuf" },
        { id: 10, name: "Kayla Cohen-Rohrbaugh", linkedin: "https://www.linkedin.com/in/kayla-cohen-rohrbaugh" },
        { id: 11, name: "Mallika Bhat", linkedin: "https://www.linkedin.com/in/mallika-bhat" },
        { id: 12, name: "Madelyn Morales", linkedin: "https://www.linkedin.com/in/madelyn-r-morales/" },
        { id: 13, name: "Olevia Tinpaw", linkedin: "https://www.linkedin.com/in/olevia-tinpaw-a115451aa/" },
        { id: 14, name: "Pedro Del Rio do Valle Coutinho", linkedin: "https://www.linkedin.com/in/pedro-del-rio-do-valle-coutinho" },
        { id: 15, name: "Ritika Pokharel", linkedin: "https://www.linkedin.com/in/ritika-pokharel133/" },
        { id: 16, name: "Ryne Acheson", linkedin: "https://www.linkedin.com/in/ryneacheson/" },
        { id: 17, name: "Sydney Richman", linkedin: "https://www.linkedin.com/in/sydney-richman-8246b01b4/" },
        { id: 18, name: "Uzochi Njiaju", linkedin: "https://www.linkedin.com/in/uzochi-njiaju/" },
        { id: 19, name: "Walid Khokhar", linkedin: "https://www.linkedin.com/in/walid-khokhar/" },
        { id: 20, name: "Zavian Johnson", linkedin: "https://www.linkedin.com/in/zavian-johnson" }
      ]
    },
    {
      "name": "Alpha Lambda",
      members: [
        { id: 1, name: "Aaron Ren", linkedin: "https://www.linkedin.com/in/aaron-ren" },
        { id: 2, name: "Alma Hagstrom", linkedin: "https://www.linkedin.com/in/alma-hagstrom/" },
        { id: 3, name: "Andrew Kim", linkedin: "https://www.linkedin.com/in/andrew-kim" },
        { id: 4, name: "Angela Luo", linkedin: "https://www.linkedin.com/in/angela-y-luo/" },
        { id: 5, name: "Ankit Penmatcha", linkedin: "https://www.linkedin.com/in/ankit-penmatcha" },
        { id: 6, name: "Arun Crispino", linkedin: "https://www.linkedin.com/in/aruncrispino/" },
        { id: 7, name: "Ben Weatherhead", linkedin: "https://www.linkedin.com/in/benjamin-weatherhead-35b8a125b/" },
        { id: 8, name: "Daniel Samuel", linkedin: "https://www.linkedin.com/in/daniel-samuel" },
        { id: 9, name: "Emily Craig", linkedin: "https://www.linkedin.com/in/emily-craig" },
        { id: 10, name: "Eric Yao", linkedin: "https://www.linkedin.com/in/eric-yao" },
        { id: 11, name: "Jason Jia", linkedin: "https://www.linkedin.com/in/jason-z-jia/" },
        { id: 12, name: "Juhi Parikh", linkedin: "https://www.linkedin.com/in/juhi-parikh/" },
        { id: 13, name: "Julia Beato", linkedin: "https://www.linkedin.com/in/julia-beato" },
        { id: 14, name: "Koena Jaware", linkedin: "https://www.linkedin.com/in/koena-jaware" },
        { id: 15, name: "Laticia Vyapuri", linkedin: "https://www.linkedin.com/in/laticia-vyapuri" },
        { id: 16, name: "Nikhail Mann", linkedin: "https://www.linkedin.com/in/nikhailmann/" },
        { id: 17, name: "Rahul Harish", linkedin: "https://www.linkedin.com/in/rahul-harish1/" },
        { id: 18, name: "Ritvik Venkat", linkedin: "https://www.linkedin.com/in/ritvik-venkat" },
        { id: 19, name: "Siri Adusumilli", linkedin: "https://www.linkedin.com/in/siri-adusumilli" },
        { id: 20, name: "Suhaib Matar", linkedin: "https://www.linkedin.com/in/suhaib-matar" },
        { id: 21, name: "Tej Mehta", linkedin: "https://www.linkedin.com/in/tej-mehta" },
        { id: 22, name: "Vyshnav Kandamath", linkedin: "https://www.linkedin.com/in/vyshnav-kandamath" }
      ]
  
    },
    {
      "name": "Alpha Kappa",
      members: [
        { id: 1, name: "Abhinav Mukherjee", linkedin: "https://www.linkedin.com/in/amukherjee1/" },
        { id: 2, name: "Alex Dong", linkedin: "https://www.linkedin.com/in/alexjdong/" },
        { id: 3, name: "Bennett Eric", linkedin: "https://www.linkedin.com/in/bennett-eric" },
        { id: 4, name: "Chen Eileen", linkedin: "https://www.linkedin.com/in/eileennchenn/" },
        { id: 5, name: "Chris Moon", linkedin: "https://www.linkedin.com/in/chris-moon-/" },
        { id: 6, name: "Grill Hudson", linkedin: "https://www.linkedin.com/in/grill-hudson" },
        { id: 7, name: "Gudwani Rohan", linkedin: "https://www.linkedin.com/in/rohan-gudwani/" },
        { id: 8, name: "Hannah Li", linkedin: "https://www.linkedin.com/in/hannah-li" },
        { id: 9, name: "Herman Jimmy", linkedin: "https://www.linkedin.com/in/jimmyherman1/" },
        { id: 10, name: "Jiayi Wang", linkedin: "https://www.linkedin.com/in/jiayi-wangg/" },
        { id: 11, name: "Kamana Karki", linkedin: "https://www.linkedin.com/in/kamana-karki" },
        { id: 12, name: "Marvi Shroff", linkedin: "https://www.linkedin.com/in/marvishroff/" },
        { id: 13, name: "Meilin Yuan", linkedin: "https://www.linkedin.com/in/meilinyuan/" },
        { id: 14, name: "Robert Xu", linkedin: "https://www.linkedin.com/in/robert-xu" },
        { id: 15, name: "So Eun Kim", linkedin: "https://www.linkedin.com/in/soekim/" },
        { id: 16, name: "Summer Sims", linkedin: "https://www.linkedin.com/in/summer-sims" },
        { id: 17, name: "Tushar Garg", linkedin: "https://www.linkedin.com/in/tushar-garg" },
        { id: 18, name: "Yusra Khan", linkedin: "https://www.linkedin.com/in/yusra-khan" }
      ]
    }
  ];